#!/usr/bin/bash

module purge
module load Perl/5.36.1-GCCcore-12.3.0
module load PostgreSQL/16.1-GCCcore-12.3.0
module load gnuplot

export PERL5LIB=/homes/daveturner/kstat/test_install/perl5_install/lib/perl5
#export PERL5LIB=/opt/beocat/kstat/perl5/

perl ./kstat.db $@

