#!/usr/bin/bash -l

module purge
module load Perl/5.36.1-GCCcore-12.3.0
module load PostgreSQL/16.1-GCCcore-12.3.0
module load gnuplot

export PERL5LIB=/opt/beocat/kstat/perl5/lib/perl5

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

perl $SCRIPT_DIR/kstat.db $@

